### ISSUE TITLE
HUD scaling - Not working

### ISSUE THREAD

**Issue by bandrews3030150** [kgrzywocz/league_of_steel#1]
Hello
As discussed via Youtube the app doesnt seem to update when league is open so, when i start up a match with in my case the health and mana setup, it loads in as Red i.e. 0% health and 0% mana, but then thats all that happens itll never update past that.
As also discussed i have attached screengrabs as best i can, but i can't seem to find logs.
![Desktop Screenshot 2020 02 05 - 17 47 22 78](https://user-images.githubusercontent.com/60688651/73868771-ff816b80-4840-11ea-85c8-875efdaa89bc.png)
![Desktop Screenshot 2020 02 05 - 17 46 22 75](https://user-images.githubusercontent.com/60688651/73868774-00b29880-4841-11ea-8049-8d4390652aed.png)
![Desktop Screenshot 2020 02 05 - 17 46 35 58](https://user-images.githubusercontent.com/60688651/73868775-00b29880-4841-11ea-9d26-245b21b5eeff.png)
![Desktop Screenshot 2020 02 05 - 17 46 38 21](https://user-images.githubusercontent.com/60688651/73868777-014b2f00-4841-11ea-8248-d3a227e09a59.png)
![Desktop Screenshot 2020 02 05 - 17 47 02 85](https://user-images.githubusercontent.com/60688651/73868778-014b2f00-4841-11ea-839f-9d2616006d85.png)

**Comment by kgrzywocz** [comment]
Hi, thanks for submitting issue. I guess i will need more info:) I will need in-game screenshot: with health and mana bars visable. Logs are currently avalable only in debug version, so you will need to build that. I can sent you .exe if you like

**Comment by bandrews3030150** [comment]
More than happy to run the debug version and I'll get screen shots of in-game footage sorted

**Comment by bandrews3030150** [comment]
![IMG_20200207_175355](https://user-images.githubusercontent.com/60688651/74055089-40ab8400-49d7-11ea-9497-57a65d072063.jpg)

**Comment by kgrzywocz** [comment]
Program is actually analyzing screen, so I need exact screenshot to analyze it:
1. In game press 'PrintScreen' on your keyboard
2. Alt+Tab to Windows
3. Open "Paint"
4. Ctrl-V paste
5. Save file

About the logs:
Here is the debug version: https://www.dropbox.com/s/hxwlwfsarygy0lu/league_of_steel_v0.4.5_debuglog.exe
1. Download it
2. Kill league_of_steel.exe running that is installed on your computer (by Task Manager -> Ctrl+Shit+Esc -> Details tab -> select league_of_steel.exe -> Click "End task"
3. Run Downloaded version
4. Play LoL
5. In folder were you run "league_of_steel_v0.4.5_debuglog.exe" log: "league_of_steel.log" should be created. Send it back to me please ;)

**Comment by bandrews3030150** [comment]
[league_of_steel.log](https://github.com/kgrzywocz/league_of_steel/files/4176614/league_of_steel.log)
![screengrab_test_LOS](https://user-images.githubusercontent.com/60688651/74099151-802db980-4b18-11ea-98ac-f70258918b41.png)

**Comment by bandrews3030150** [comment]
Ok so after a few games of league its clicked to what the issue is. When thinking into how the app is taking the information (assuming im understanding correct) i wondered whether it wasn't working due to hud scaling. I prefer to play league with as much space as possible so i scale the hud to 0%, during a game i increased it to 50% (as is default) but no luck, when i scaled the hud 83% or above it began to update and present correct information.

**Comment by kgrzywocz** [comment]
A I get it. Hud scaling is not supported yet - I guess you need so I will see how much work is needed ;)

**Comment by kgrzywocz** [comment]
It seams to be doable ;) I already got scaling algorithm and the settings seams GlobalScale in [HUD] section of <game dir>/Config/game.cfm
I will need some time to implement reading of that. If you want something fast send me your value and I can sent you hard coded version or you can build one your self ;)

**Comment by bandrews3030150** [comment]
Im fine with waiting, i run the hud on the smallest setting i think its either 0% or 1%.

**Comment by kgrzywocz** [comment]
Ok here is version with hardcoded GlobalScale=0.01: https://www.dropbox.com/s/1vp1l1speouiu9g/league_of_steel_v0.5.0-pre_minimalhud_setup.exe

I am unable to test it properly now, but it should work ;)
When I find some time with computer running LoL I will try to write proper version(reading config), then I will let you know

**Comment by kgrzywocz** [comment]
Hi again, I made some changes in v0.5.0-pre version. It should work - I would be glad if you could test it, please ;)

**Comment by bandrews3030150** [comment]
Hi again, sorry have been testing the hardcoded over the last week when able to, it's working well but with a few quirks (as expected in early version)
* I have moved the scale up to 5 from 0 as it has a tendency to flash randomly.
* When respawning there is a strange delay on the update of information (not everytime)
* The HIT doesn't react on every hit (not sure if as planned)

**Comment by kgrzywocz** [comment]
Thanks a lot for feedback.
Ad 1. Hmm... Maybe I need to tweak a bit values for hud scaling - > I will try to play with it
Ad 2. Any particular symptoms? Does rest of game runs smoothly? It might be worse on newer version - Am I correct?
Ad 3. Hit reacts only on critical hits - unfortunately it also needs also to least around 200ms. You want it to behave differently? I could also see the change in HP and react on every decrement..

**Comment by kgrzywocz** [comment]
It seams like hud scaling is working now ;) I found some problems with different resolution ratio - I tried to improve that. v0.5 is out now - if you have another issues let me know or open another issue ;)
Thanks a lot for your time and support ;)
