### ISSUE TITLE
cool down timer for prism

### ISSUE THREAD

**Issue by mjun0425** [kgrzywocz/league_of_steel#4]
please add q w e r cooltime and summoner's spell (flash, cleanse..etc)
-----------------
it is really good for gamers like me!!

the mp rgb really improved my lol skill...

**Comment by mjun0425** [comment]
is it possible? is it image catching method or api data method?...
----------------
like dota2 gamesense, please add item cooldown, spell cooldown, Crowd control state rgb !!
ps. You are my hero. I found this github when I was frustrated because I couldn't find gamesense engine for steelseries prism. Thank you very much.

**Comment by kgrzywocz** [comment]
Is mentioned on YT: I splited this issue:
lol skills (qwer) cooltime #5
lol summoner's spell(df) cooldown #6
There are propably 2 more: timer (?) and prism issues, but I guess I need some more info
